version: "3"
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: fixme_backend_development
      POSTGRES_USER: USER
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/ossn/fixme_backend/
    environment:
      DATABASE_URL: "postgres://USER:PASSWORD@db:5432/fixme_backend_development?sslmode=disable"
      GITHUB_TOKEN: "698ce2d4343b5a4db8dd443817d68b10287b8bd6"
      GITLAB_TOKEN: "x7P_6CZ3zXP9zW741iQx"
      JWT_SECRET: "ADD_A_JWT_SECRET"
    ports:
      - 3000:3000
    links:
      - db:db
