version: "3"
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: fixme_backend_development
      POSTGRES_USER: USER
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/ossn/fixme_backend/
    environment:
      DATABASE_URL: "postgres://USER:PASSWORD@db:5432/fixme_backend_development?sslmode=disable"
      GITHUB_TOKEN: "5aaaa0369e2219ea53680c4368fa8066716dd9ac"
      GITLAB_TOKEN: "3pnz2a1NhP5txyXL9q1Q"
      JWT_SECRET: "ADD_A_JWT_SECRET"
      REDIS_SERVER: "cache:6379"
    ports:
      - 3000:3000
    links:
      - db:db
      - cache:cache
  cache:
    image: redis:5.0
